[project]
name = "climate-trace"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "David Gasquez", email = "davidgasquez@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pyzmq>=27.1.0",
]
